; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	G:\내 드라이브\SOURCE\CPP\1\06_FUNCTION2\constexpr_function2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?add@@YAHHH@Z					; add
PUBLIC	_main
; Function compile flags: /Ogtpy
; File g:\내 드라이브\source\cpp\1\06_function2\constexpr_function2.cpp
;	COMDAT _main
_TEXT	SEGMENT
_main	PROC						; COMDAT

; 8    :     int n1 = add(1,2);
; 9    :     int n2 = add(n1,2);
; 10   : }

	xor	eax, eax
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
; File g:\내 드라이브\source\cpp\1\06_function2\constexpr_function2.cpp
;	COMDAT ?add@@YAHHH@Z
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?add@@YAHHH@Z PROC					; add, COMDAT

; 3    :     return a + b;

	mov	eax, DWORD PTR _a$[esp-4]
	add	eax, DWORD PTR _b$[esp-4]

; 4    : }

	ret	0
?add@@YAHHH@Z ENDP					; add
_TEXT	ENDS
END
