; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27023.1 

	TITLE	G:\내 드라이브\SOURCE\CPP\1\05_FUNCTION1\inline2.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?add1@@YAHHH@Z					; add1
PUBLIC	_main
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\05_function1\inline2.cpp
_TEXT	SEGMENT
_n2$ = -8						; size = 4
_n1$ = -4						; size = 4
_main	PROC

; 13   : {

	push	ebp
	mov	ebp, esp
	sub	esp, 8

; 14   :     int n1 = add1(1,2); // 호출

	push	2
	push	1
	call	?add1@@YAHHH@Z				; add1
	add	esp, 8
	mov	DWORD PTR _n1$[ebp], eax

; 9    :     return a + b;

	mov	eax, 1
	add	eax, 2

; 15   :     int n2 = add2(1,2); // 치환

	mov	DWORD PTR _n2$[ebp], eax

; 16   : }

	xor	eax, eax
	mov	esp, ebp
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
; File g:\내 드라이브\source\cpp\1\05_function1\inline2.cpp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
?add1@@YAHHH@Z PROC					; add1

; 3    : {

	push	ebp
	mov	ebp, esp

; 4    :     return a + b;

	mov	eax, DWORD PTR _a$[ebp]
	add	eax, DWORD PTR _b$[ebp]

; 5    : }

	pop	ebp
	ret	0
?add1@@YAHHH@Z ENDP					; add1
_TEXT	ENDS
END
